// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPvhu4TqbBIZvrTjJpd94c6d0FD_DiXqs',
    appId: '1:729459310329:web:313c8608b6b7bfb61aec28',
    messagingSenderId: '729459310329',
    projectId: 'simplified-ordering-system',
    authDomain: 'simplified-ordering-system.firebaseapp.com',
    storageBucket: 'simplified-ordering-system.appspot.com',
    measurementId: 'G-8M6QRCMJYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfT_7V9laOVbeMZMbMwn8DCBo_Y-1TsrY',
    appId: '1:729459310329:android:1bf2579c423d1eac1aec28',
    messagingSenderId: '729459310329',
    projectId: 'simplified-ordering-system',
    storageBucket: 'simplified-ordering-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9epC7o3zUB3Owx7LGGuVmi3QI1N88EaY',
    appId: '1:729459310329:ios:bbd3865fd67ec7f81aec28',
    messagingSenderId: '729459310329',
    projectId: 'simplified-ordering-system',
    storageBucket: 'simplified-ordering-system.appspot.com',
    iosBundleId: 'com.example.orderingSystemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9epC7o3zUB3Owx7LGGuVmi3QI1N88EaY',
    appId: '1:729459310329:ios:2bd4ccb3d1ffa3a21aec28',
    messagingSenderId: '729459310329',
    projectId: 'simplified-ordering-system',
    storageBucket: 'simplified-ordering-system.appspot.com',
    iosBundleId: 'com.example.orderingSystemApp.RunnerTests',
  );
}
